export interface LocalityData {
  slug: string;
  name: string;
  city: string;
  citySlug: string;
  landmark: string;
  pinCodes: string[];
  description: string;
  waterQualityNote: string;
  nearbyAreas: string[];
  keywords: string[];
}

export const bangaloreLocalities: LocalityData[] = [
  {
    slug: 'whitefield',
    name: 'Whitefield',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'ITPL (International Tech Park)',
    pinCodes: ['560066', '560067'],
    description: 'Whitefield is one of Bengaluru\'s most prominent IT hubs, home to ITPL, numerous tech parks, and a rapidly growing residential population. With thousands of apartments and PG accommodations, the demand for clean drinking water solutions is immense.',
    waterQualityNote: 'Whitefield\'s water supply often comes from borewells with high TDS levels (500-1200 ppm). Municipal Cauvery water supply is limited in many newer layouts, making an RO purifier essential for safe drinking water.',
    nearbyAreas: ['Marathahalli', 'Hoodi', 'Varthur', 'KR Puram', 'Brookefield'],
    keywords: [
      'RO purifier on rent Whitefield', 'best RO rental Whitefield', 'cheap RO purifier Whitefield',
      'RO service Whitefield', 'RO repair Whitefield', 'water purifier rental Whitefield',
      'RO AMC Whitefield', 'RO installation Whitefield', 'RO purifier near me Whitefield',
      'RO rent price Whitefield', 'water purifier on rent in Whitefield Bangalore',
      'best water purifier Whitefield', 'RO water filter Whitefield',
      'drinking water purifier Whitefield', 'water purifier service Whitefield',
    ],
  },
  {
    slug: 'sarjapur-road',
    name: 'Sarjapur Road',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Wipro Corporate Office',
    pinCodes: ['560035', '560102', '562125'],
    description: 'Sarjapur Road is a fast-developing residential and IT corridor in South-East Bengaluru. Connecting major tech hubs like Electronic City, Bellandur, and Whitefield, it\'s a prime location for working professionals seeking quality living.',
    waterQualityNote: 'Sarjapur Road predominantly relies on borewell water with TDS levels ranging from 600 to 1500 ppm. Cauvery water supply is limited, making a reliable RO purifier a necessity for most households.',
    nearbyAreas: ['Bellandur', 'HSR Layout', 'Electronic City', 'Varthur', 'Hosa Road'],
    keywords: [
      'RO purifier on rent Sarjapur Road', 'best RO rental Sarjapur Road', 'cheap RO Sarjapur Road',
      'RO service Sarjapur Road', 'RO repair Sarjapur Road', 'water purifier rental Sarjapur Road',
      'RO AMC Sarjapur Road', 'RO installation Sarjapur Road', 'RO near me Sarjapur Road',
      'RO price Sarjapur Road', 'water purifier on rent Sarjapur',
      'best water purifier Sarjapur Road Bangalore', 'RO purifier Sarjapur',
    ],
  },
  {
    slug: 'electronic-city',
    name: 'Electronic City',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Infosys Campus',
    pinCodes: ['560100', '560099'],
    description: 'Electronic City is Bengaluru\'s first and largest IT hub, housing corporate campuses of Infosys, Wipro, TCS, and many more. With a massive working population and thousands of residential apartments, it\u2019s a key market for affordable water purification solutions.',
    waterQualityNote: 'Electronic City and its surrounding areas have inconsistent water supply. Most apartments rely on tanker water or borewells with TDS levels exceeding 800 ppm. A good RO system is critical for safe consumption.',
    nearbyAreas: ['Sarjapur Road', 'Bommasandra', 'HSR Layout', 'BTM Layout', 'Hosur Road'],
    keywords: [
      'RO purifier on rent Electronic City', 'best RO rental Electronic City', 'cheap RO Electronic City',
      'RO service Electronic City', 'RO repair Electronic City', 'water purifier rental Electronic City',
      'RO AMC Electronic City', 'RO installation Electronic City', 'RO near me Electronic City',
      'RO rent price Electronic City', 'water purifier on rent Electronic City Bangalore',
      'best water purifier Electronic City', 'RO water filter Electronic City',
    ],
  },
  {
    slug: 'hsr-layout',
    name: 'HSR Layout',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'HSR BDA Complex',
    pinCodes: ['560102', '560034'],
    description: 'HSR Layout is a well-planned residential locality in South Bengaluru known for its startup ecosystem, excellent dining options, and vibrant community. It\'s a preferred choice for young professionals and families alike.',
    waterQualityNote: 'HSR Layout has partial Cauvery water supply but many blocks still rely on borewells. TDS levels vary from 300 to 900 ppm depending on the sector, making an RO purifier a smart investment.',
    nearbyAreas: ['BTM Layout', 'Koramangala', 'Bellandur', 'Sarjapur Road', 'Bommanahalli'],
    keywords: [
      'RO purifier on rent HSR Layout', 'best RO rental HSR Layout', 'cheap RO purifier HSR Layout',
      'RO service HSR Layout', 'RO repair HSR Layout', 'water purifier rental HSR Layout',
      'RO AMC HSR Layout', 'RO installation HSR Layout', 'RO near me HSR Layout',
      'RO rent price HSR Layout', 'water purifier on rent HSR Layout Bangalore',
    ],
  },
  {
    slug: 'marathahalli',
    name: 'Marathahalli',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Marathahalli Bridge',
    pinCodes: ['560037'],
    description: 'Marathahalli is a major residential and commercial hub in East Bengaluru, strategically located near the Outer Ring Road. It\'s packed with IT professionals, PG accommodations, and apartments — making it one of the highest-demand areas for rental water purifiers.',
    waterQualityNote: 'Marathahalli primarily depends on borewell water with moderate to high TDS (400-1000 ppm). The water often has an unpleasant taste and odor, making RO purification essential.',
    nearbyAreas: ['Whitefield', 'Bellandur', 'Varthur', 'Brookefield', 'Kundalahalli'],
    keywords: [
      'RO purifier on rent Marathahalli', 'best RO rental Marathahalli', 'cheap RO purifier Marathahalli',
      'RO service Marathahalli', 'RO repair Marathahalli', 'water purifier rental Marathahalli',
      'RO AMC Marathahalli', 'RO installation Marathahalli', 'RO near me Marathahalli',
      'RO rent price Marathahalli', 'water purifier on rent Marathahalli Bangalore',
    ],
  },
  {
    slug: 'bellandur',
    name: 'Bellandur',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Bellandur Lake',
    pinCodes: ['560103'],
    description: 'Bellandur is a rapidly growing residential area along the Outer Ring Road, with numerous gated communities and apartment complexes. Its proximity to major IT corridors makes it a popular choice for tech professionals.',
    waterQualityNote: 'Bellandur heavily depends on tanker water and borewells. Water quality can be poor with high TDS and occasional contamination from the lake area. An RO purifier is highly recommended.',
    nearbyAreas: ['HSR Layout', 'Sarjapur Road', 'Marathahalli', 'Varthur', 'Koramangala'],
    keywords: [
      'RO purifier on rent Bellandur', 'best RO rental Bellandur', 'cheap RO purifier Bellandur',
      'RO service Bellandur', 'RO repair Bellandur', 'water purifier rental Bellandur',
      'RO AMC Bellandur', 'RO installation Bellandur', 'RO near me Bellandur',
      'RO rent price Bellandur', 'water purifier on rent Bellandur Bangalore',
    ],
  },
  {
    slug: 'hebbal',
    name: 'Hebbal',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Hebbal Flyover',
    pinCodes: ['560024', '560032'],
    description: 'Hebbal is a prominent area in North Bengaluru, known for the Hebbal Flyover junction that connects to the airport road. It has seen tremendous residential development and is home to many premium apartments and tech parks.',
    waterQualityNote: 'Hebbal enjoys partial Cauvery water supply, but many newer complexes rely on borewells with TDS levels between 400-800 ppm. Regular RO maintenance is recommended.',
    nearbyAreas: ['Yelahanka', 'Sahakara Nagar', 'RT Nagar', 'Bellary Road', 'Nagavara'],
    keywords: [
      'RO purifier on rent Hebbal', 'best RO rental Hebbal', 'cheap RO purifier Hebbal',
      'RO service Hebbal', 'RO repair Hebbal', 'water purifier rental Hebbal',
      'RO AMC Hebbal', 'RO installation Hebbal', 'RO near me Hebbal',
      'RO rent price Hebbal', 'water purifier on rent Hebbal Bangalore',
    ],
  },
  {
    slug: 'yelahanka',
    name: 'Yelahanka',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Yelahanka Air Force Station',
    pinCodes: ['560064', '560065'],
    description: 'Yelahanka is a well-established suburb in North Bengaluru, close to Kempegowda International Airport. It has a mix of independent houses and modern apartments, making it a family-friendly locality with growing infrastructure.',
    waterQualityNote: 'Yelahanka predominantly uses borewell water with moderate TDS levels (300-700 ppm). Some areas receive Cauvery supply but not consistently. An RO system ensures safe daily drinking water.',
    nearbyAreas: ['Hebbal', 'Jakkur', 'Thanisandra', 'Sahakara Nagar', 'Devanahalli'],
    keywords: [
      'RO purifier on rent Yelahanka', 'best RO rental Yelahanka', 'cheap RO purifier Yelahanka',
      'RO service Yelahanka', 'RO repair Yelahanka', 'water purifier rental Yelahanka',
      'RO AMC Yelahanka', 'RO installation Yelahanka', 'RO near me Yelahanka',
      'RO rent price Yelahanka', 'water purifier on rent Yelahanka Bangalore',
    ],
  },
  {
    slug: 'btm-layout',
    name: 'BTM Layout',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'BTM Lake (Madiwala)',
    pinCodes: ['560029', '560076'],
    description: 'BTM Layout is a buzzing residential area in South Bengaluru, known for its affordable rents and proximity to Silk Board, Electronic City, and Koramangala. It\'s densely populated with young professionals and students.',
    waterQualityNote: 'BTM Layout has access to Cauvery water in many areas, but supply is often inconsistent. Many residents supplement with borewells or tanker water, making an RO purifier a practical solution.',
    nearbyAreas: ['HSR Layout', 'Koramangala', 'JP Nagar', 'Bommanahalli', 'Electronic City'],
    keywords: [
      'RO purifier on rent BTM Layout', 'best RO rental BTM Layout', 'cheap RO purifier BTM Layout',
      'RO service BTM Layout', 'RO repair BTM Layout', 'water purifier rental BTM Layout',
      'RO AMC BTM Layout', 'RO installation BTM Layout', 'RO near me BTM Layout',
      'RO rent price BTM Layout', 'water purifier on rent BTM Layout Bangalore',
    ],
  },
  {
    slug: 'jp-nagar',
    name: 'JP Nagar',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Iskon Temple JP Nagar',
    pinCodes: ['560078', '560062'],
    description: 'JP Nagar (Jayaprakash Narayan Nagar) is a well-developed residential area in South Bengaluru. Known for its tree-lined streets, excellent schools, and shopping centers, it\'s a preferred locality for families.',
    waterQualityNote: 'JP Nagar has relatively good Cauvery water supply in older phases, but newer developments and higher phases may rely on borewells with TDS levels of 300-600 ppm.',
    nearbyAreas: ['BTM Layout', 'Banashankari', 'Jayanagar', 'Kumaraswamy Layout', 'Uttarahalli'],
    keywords: [
      'RO purifier on rent JP Nagar', 'best RO rental JP Nagar', 'cheap RO purifier JP Nagar',
      'RO service JP Nagar', 'RO repair JP Nagar', 'water purifier rental JP Nagar',
      'RO AMC JP Nagar', 'RO installation JP Nagar', 'RO near me JP Nagar',
      'RO rent price JP Nagar', 'water purifier on rent JP Nagar Bangalore',
    ],
  },
  {
    slug: 'indiranagar',
    name: 'Indiranagar',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: '100 Feet Road',
    pinCodes: ['560038', '560008'],
    description: 'Indiranagar is one of Bengaluru\'s most upscale and vibrant neighbourhoods, famous for its nightlife on 100 Feet Road, boutique stores, and premium residences. It attracts a mix of young professionals, expats, and established families.',
    waterQualityNote: 'Indiranagar benefits from Cauvery water supply in most areas, with relatively lower TDS (200-500 ppm). However, an RO purifier is still recommended for consistent water quality and taste.',
    nearbyAreas: ['Koramangala', 'Domlur', 'Old Airport Road', 'Ulsoor', 'Jeevanbhima Nagar'],
    keywords: [
      'RO purifier on rent Indiranagar', 'best RO rental Indiranagar', 'cheap RO purifier Indiranagar',
      'RO service Indiranagar', 'RO repair Indiranagar', 'water purifier rental Indiranagar',
      'RO AMC Indiranagar', 'RO installation Indiranagar', 'RO near me Indiranagar',
      'RO rent price Indiranagar', 'water purifier on rent Indiranagar Bangalore',
    ],
  },
  {
    slug: 'kr-puram',
    name: 'KR Puram',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'KR Puram Railway Station',
    pinCodes: ['560036', '560049'],
    description: 'KR Puram (Krishnarajapuram) is one of the oldest suburbs of Bengaluru, located on the eastern side. It\'s a major transport hub with a railway station and connections to Whitefield, Old Madras Road, and the ORR.',
    waterQualityNote: 'KR Puram has mixed water sources — some areas get Cauvery supply while others depend on borewells with TDS levels of 500-1200 ppm. Consistent RO purification is essential.',
    nearbyAreas: ['Whitefield', 'Hoodi', 'Mahadevapura', 'Ramamurthy Nagar', 'Tin Factory'],
    keywords: [
      'RO purifier on rent KR Puram', 'best RO rental KR Puram', 'cheap RO purifier KR Puram',
      'RO service KR Puram', 'RO repair KR Puram', 'water purifier rental KR Puram',
      'RO AMC KR Puram', 'RO installation KR Puram', 'RO near me KR Puram',
      'RO rent price KR Puram', 'water purifier on rent KR Puram Bangalore',
    ],
  },
  {
    slug: 'hoodi',
    name: 'Hoodi',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Hoodi Circle',
    pinCodes: ['560048'],
    description: 'Hoodi is a fast-growing residential area nestled between Whitefield and KR Puram. With affordable housing options and proximity to major IT parks like ITPL and RMZ Ecoworld, it has become a hotspot for working professionals.',
    waterQualityNote: 'Hoodi relies heavily on borewell water with TDS levels varying from 500-1000 ppm. Municipal water supply is expanding but remains limited in many apartment complexes.',
    nearbyAreas: ['Whitefield', 'KR Puram', 'Brookefield', 'Mahadevapura', 'Marathahalli'],
    keywords: [
      'RO purifier on rent Hoodi', 'best RO rental Hoodi', 'cheap RO purifier Hoodi',
      'RO service Hoodi', 'RO repair Hoodi', 'water purifier rental Hoodi',
      'RO AMC Hoodi', 'RO installation Hoodi', 'RO near me Hoodi',
      'RO rent price Hoodi', 'water purifier on rent Hoodi Bangalore',
    ],
  },
  {
    slug: 'varthur',
    name: 'Varthur',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Varthur Lake',
    pinCodes: ['560087'],
    description: 'Varthur is a rapidly developing suburb on the eastern edge of Bengaluru, adjacent to Whitefield and Sarjapur Road. It offers relatively affordable housing and is attracting many new apartment projects.',
    waterQualityNote: 'Varthur almost entirely depends on borewell water with high TDS levels (700-1500 ppm). The water quality is among the poorest in Bengaluru, making a high-quality RO purifier absolutely essential.',
    nearbyAreas: ['Whitefield', 'Bellandur', 'Sarjapur Road', 'Marathahalli', 'Hoodi'],
    keywords: [
      'RO purifier on rent Varthur', 'best RO rental Varthur', 'cheap RO purifier Varthur',
      'RO service Varthur', 'RO repair Varthur', 'water purifier rental Varthur',
      'RO AMC Varthur', 'RO installation Varthur', 'RO near me Varthur',
      'RO rent price Varthur', 'water purifier on rent Varthur Bangalore',
    ],
  },
  {
    slug: 'banashankari',
    name: 'Banashankari',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Banashankari Temple',
    pinCodes: ['560070', '560085'],
    description: 'Banashankari is a large, well-established residential area in South Bengaluru. Named after the famous Banashankari Amma Temple, it\'s known for its cultural significance, excellent connectivity, and family-oriented atmosphere.',
    waterQualityNote: 'Banashankari has good Cauvery water supply in older stages, with lower TDS (200-400 ppm). However, newer stages and extensions may rely on borewells, where an RO purifier is beneficial.',
    nearbyAreas: ['JP Nagar', 'Jayanagar', 'Kumaraswamy Layout', 'Kanakapura Road', 'Girinagar'],
    keywords: [
      'RO purifier on rent Banashankari', 'best RO rental Banashankari', 'cheap RO purifier Banashankari',
      'RO service Banashankari', 'RO repair Banashankari', 'water purifier rental Banashankari',
      'RO AMC Banashankari', 'RO installation Banashankari', 'RO near me Banashankari',
      'RO rent price Banashankari', 'water purifier on rent Banashankari Bangalore',
    ],
  },
  {
    slug: 'rajajinagar',
    name: 'Rajajinagar',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Orion Mall',
    pinCodes: ['560010', '560021'],
    description: 'Rajajinagar is a well-planned residential locality in West Bengaluru, close to the city center. It\'s known for its commercial establishments along Dr. Rajkumar Road and proximity to Orion Mall and the metro line.',
    waterQualityNote: 'Rajajinagar has one of the better Cauvery water supply networks in Bengaluru, with TDS levels typically between 150-350 ppm. An RO purifier still offers added protection for taste and safety.',
    nearbyAreas: ['Malleshwaram', 'Vijayanagar', 'Mahalakshmipuram', 'Basaveshwara Nagar', 'Yeshwanthpur'],
    keywords: [
      'RO purifier on rent Rajajinagar', 'best RO rental Rajajinagar', 'cheap RO purifier Rajajinagar',
      'RO service Rajajinagar', 'RO repair Rajajinagar', 'water purifier rental Rajajinagar',
      'RO AMC Rajajinagar', 'RO installation Rajajinagar', 'RO near me Rajajinagar',
      'RO rent price Rajajinagar', 'water purifier on rent Rajajinagar Bangalore',
    ],
  },
  {
    slug: 'malleshwaram',
    name: 'Malleshwaram',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Mantri Mall',
    pinCodes: ['560003', '560055'],
    description: 'Malleshwaram is one of Bengaluru\'s oldest and most charming neighbourhoods, known for its tree-lined streets, heritage temples, and iconic food joints. It combines old-world charm with modern amenities.',
    waterQualityNote: 'Malleshwaram enjoys excellent Cauvery water supply with consistently low TDS (150-300 ppm). However, some older buildings may have pipe contamination, where an RO purifier provides extra safety.',
    nearbyAreas: ['Rajajinagar', 'Sadashivanagar', 'Sanjaynagar', 'Basaveshwara Nagar', 'Yeshwanthpur'],
    keywords: [
      'RO purifier on rent Malleshwaram', 'best RO rental Malleshwaram', 'cheap RO purifier Malleshwaram',
      'RO service Malleshwaram', 'RO repair Malleshwaram', 'water purifier rental Malleshwaram',
      'RO AMC Malleshwaram', 'RO installation Malleshwaram', 'RO near me Malleshwaram',
      'RO rent price Malleshwaram', 'water purifier on rent Malleshwaram Bangalore',
    ],
  },
  {
    slug: 'koramangala',
    name: 'Koramangala',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Forum Mall',
    pinCodes: ['560034', '560095'],
    description: 'Koramangala is Bengaluru\'s startup capital and one of the most sought-after neighbourhoods in the city. With a vibrant mix of restaurants, pubs, co-working spaces, and premium residences, it\'s the heartbeat of young Bengaluru.',
    waterQualityNote: 'Koramangala has decent Cauvery supply in most blocks with TDS of 200-500 ppm. Some areas near the lake may have contamination concerns, making RO purification a wise choice.',
    nearbyAreas: ['Indiranagar', 'HSR Layout', 'BTM Layout', 'Ejipura', 'Domlur'],
    keywords: [
      'RO purifier on rent Koramangala', 'best RO rental Koramangala', 'cheap RO purifier Koramangala',
      'RO service Koramangala', 'RO repair Koramangala', 'water purifier rental Koramangala',
      'RO AMC Koramangala', 'RO installation Koramangala', 'RO near me Koramangala',
      'RO rent price Koramangala', 'water purifier on rent Koramangala Bangalore',
    ],
  },
  {
    slug: 'jayanagar',
    name: 'Jayanagar',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Jayanagar Shopping Complex',
    pinCodes: ['560011', '560041', '560069'],
    description: 'Jayanagar is one of Bengaluru\'s most elegant and well-planned residential areas, known for its excellent infrastructure, wide roads, and proximity to commercial centers like South End Circle and Lalbagh.',
    waterQualityNote: 'Jayanagar has excellent Cauvery water supply with low TDS (150-300 ppm). It\'s one of the better-served areas. However, RO purification remains popular for extra safety and improved taste.',
    nearbyAreas: ['JP Nagar', 'BTM Layout', 'Banashankari', 'Basavanagudi', 'Koramangala'],
    keywords: [
      'RO purifier on rent Jayanagar', 'best RO rental Jayanagar', 'cheap RO purifier Jayanagar',
      'RO service Jayanagar', 'RO repair Jayanagar', 'water purifier rental Jayanagar',
      'RO AMC Jayanagar', 'RO installation Jayanagar', 'RO near me Jayanagar',
      'RO rent price Jayanagar', 'water purifier on rent Jayanagar Bangalore',
    ],
  },
  {
    slug: 'thanisandra',
    name: 'Thanisandra',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Manyata Tech Park',
    pinCodes: ['560077'],
    description: 'Thanisandra is a rapidly developing area in North Bengaluru, located close to Manyata Tech Park and the Outer Ring Road. It has witnessed a surge in apartment projects and is popular among IT professionals.',
    waterQualityNote: 'Thanisandra mainly relies on borewell water with TDS levels of 400-900 ppm. Cauvery water supply is gradually expanding but isn\'t consistent yet.',
    nearbyAreas: ['Hebbal', 'Nagavara', 'Yelahanka', 'Jakkur', 'Sahakara Nagar'],
    keywords: [
      'RO purifier on rent Thanisandra', 'best RO rental Thanisandra', 'cheap RO purifier Thanisandra',
      'RO service Thanisandra', 'RO repair Thanisandra', 'water purifier rental Thanisandra',
      'RO AMC Thanisandra', 'RO installation Thanisandra', 'RO near me Thanisandra',
      'RO rent price Thanisandra', 'water purifier on rent Thanisandra Bangalore',
    ],
  },
  {
    slug: 'bommanahalli',
    name: 'Bommanahalli',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Silk Board Junction',
    pinCodes: ['560068'],
    description: 'Bommanahalli is a well-connected residential area near Silk Board Junction in South Bengaluru. It serves as a gateway to Electronic City and HSR Layout, making it popular among IT employees looking for affordable housing.',
    waterQualityNote: 'Bommanahalli has a mix of Cauvery and borewell water supply. TDS levels are moderate (300-700 ppm), and water quality varies by block. An RO purifier ensures consistent quality.',
    nearbyAreas: ['HSR Layout', 'BTM Layout', 'Electronic City', 'Begur', 'Arekere'],
    keywords: [
      'RO purifier on rent Bommanahalli', 'best RO rental Bommanahalli', 'cheap RO purifier Bommanahalli',
      'RO service Bommanahalli', 'RO repair Bommanahalli', 'water purifier rental Bommanahalli',
      'RO AMC Bommanahalli', 'RO installation Bommanahalli', 'RO near me Bommanahalli',
      'RO rent price Bommanahalli', 'water purifier on rent Bommanahalli Bangalore',
    ],
  },
  {
    slug: 'mahadevapura',
    name: 'Mahadevapura',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'Phoenix Marketcity',
    pinCodes: ['560048'],
    description: 'Mahadevapura is one of Bengaluru\'s fastest-growing zones, home to the Outer Ring Road tech corridor, RMZ Ecoworld, and Phoenix Marketcity. The residential real estate boom has made it a key market for home services.',
    waterQualityNote: 'Mahadevapura has limited Cauvery supply with most buildings using borewells (TDS: 500-1200 ppm). Water quality is a common complaint among residents.',
    nearbyAreas: ['Whitefield', 'Hoodi', 'KR Puram', 'Kadugodi', 'Brookefield'],
    keywords: [
      'RO purifier on rent Mahadevapura', 'best RO rental Mahadevapura', 'cheap RO purifier Mahadevapura',
      'RO service Mahadevapura', 'RO repair Mahadevapura', 'water purifier rental Mahadevapura',
      'RO AMC Mahadevapura', 'RO installation Mahadevapura', 'RO near me Mahadevapura',
      'RO rent price Mahadevapura', 'water purifier on rent Mahadevapura Bangalore',
    ],
  },
  {
    slug: 'kanakapura-road',
    name: 'Kanakapura Road',
    city: 'Bengaluru',
    citySlug: 'bengaluru',
    landmark: 'NICE Road Junction',
    pinCodes: ['560062', '560082'],
    description: 'Kanakapura Road is an emerging residential corridor in South-West Bengaluru. With the metro line extending here and numerous villa projects, it\'s rapidly becoming a preferred location for families seeking a quieter lifestyle.',
    waterQualityNote: 'Kanakapura Road has limited municipal water supply. Most homes depend on borewells with TDS levels of 500-1000 ppm. A reliable RO system is essential for daily water needs.',
    nearbyAreas: ['JP Nagar', 'Banashankari', 'Uttarahalli', 'Konanakunte', 'Art of Living Ashram'],
    keywords: [
      'RO purifier on rent Kanakapura Road', 'best RO rental Kanakapura Road', 'cheap RO purifier Kanakapura Road',
      'RO service Kanakapura Road', 'RO repair Kanakapura Road', 'water purifier rental Kanakapura Road',
      'RO AMC Kanakapura Road', 'RO installation Kanakapura Road', 'RO near me Kanakapura Road',
      'RO rent price Kanakapura Road', 'water purifier on rent Kanakapura Road Bangalore',
    ],
  },
];

// Helper to find a locality by slug
export const getLocalityBySlug = (slug: string): LocalityData | undefined => {
  return bangaloreLocalities.find(l => l.slug === slug);
};

// Get all locality slugs for static generation
export const getAllLocalitySlugs = (): string[] => {
  return bangaloreLocalities.map(l => l.slug);
};
